azure:
  subscription_id: 70b4b1fd-03a3-4a87-b662-2742346c740c
  resource_group: rg-representation-learning-dev
  location: northeurope

storage:
  account_name: reprlearnnishantdev
  account_url: https://reprlearnnishantdev.blob.core.windows.net
  table_endpoint: https://reprlearnnishantdev.table.core.windows.net
  metadata_table: imagemetadata
  raw_container: raw-images
  quarantine_container: quarantined-images
  accepted_container: accepted-images
  dataset_manifest_container: dataset-manifests

machine_learning:
  workspace_name: null
  compute_cluster_name: gpu-cluster
  vm_size: Standard_NC4as_T4_v3
  registered_model_name: image-encoder

vector_store:
  search_service_name: null
  active_index_alias: image-embeddings-active

feature_store:
  name: image-feature-store
  offline_store: adls
  online_store: managed_redis

deployment:
  container_registry_name: null
  container_app_environment: image-platform-environment
  inference_app_name: image-inference-api

messaging:
  fully_qualified_namespace: sb-reprlearn-nishant-dev.servicebus.windows.net
  ingestion_queue: image-ingestion